### PR TITLE
Deal with memory leak

### PR DESCRIPTION
**Pull request by lattwood**
In a high throughput environment, the two goroutines being scheduled by
Count and Timing are never getting scheduled. This results in memory
usage going through the roof.

Because the datadog uses UDP for the sends, they're not going to block.

### CODE REVIEW

**Comment by bonds0097** [comment]
In the past, we had issues where UDP timeouts in a high throughput were in fact causing stat calls to block, which resulted in slowing down workers significantly. This is why this stuff was moved to goroutines.

**Comment by lattwood** [comment]
That sounds like a better alternative than letting apps die, due to unbounded memory usage.

Any tickets around the UDP timeout issue? I'm curious about that now.

**Comment by bonds0097** [comment]
This was a long time ago.

And it's definitely not better given that the 'app dying' issue seems to be isolated to a single app but the UDP timeouts were affects all of our workers in some really bad ways, i.e. an ssl scan would take 2s but then have a 5s. udp timeout block, killing performance.

Also, not sure I understand how this would lead to unbound mem usage given that golang has a hard goroutine limit of 8192 or something?

**Comment by rikonor** [comment]
I seem to recall that with the original stats implementation every call to
Count or Timing would initialize a new client and a new connection, which
would really make sense to cause blocking. I personally am not convinced
that once the connection is made and held, it's necessary to spawn go
routines, I think in those cases it might be better to sample the stats
(See SampleStatser). That said, if it works with the go routines, I don't
have any objections.

**Comment by lattwood** [comment]
Looking at the source code for the DataDog integration they reuse the same connection.

https://github.com/DataDog/datadog-go/blob/master/statsd/statsd.go#L222-L235

This should solve the memory issues on the importer.

**Pull request merged**
